name: Publish new version

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - package.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@v4

      - name: Publish to NPM
        run: |
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN_NPM }}

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Configure git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "mehdi.habaru@gmail.com"

      - name: Check out to ts-entity
        uses: actions/checkout@v4
        with:
          repository: Mirodeon/ts-entity
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          path: ts-entity

      - name: Refresh ts-entity
        run: |
          cd ts-entity
          npm-check-updates @mirodeon/ts-core -u
          git add --all
          git commit -m "Refresh version of ts-core"
          npm version patch -m "New version of ts-entity"
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN_NPM }}